[32minfo[39m: Database connection established successfully {"timestamp":"2025-06-27T09:19:00.031Z"}
[32minfo[39m: Database synchronized successfully {"timestamp":"2025-06-27T09:19:00.920Z"}
[32minfo[39m: Server running on port 3000 {"timestamp":"2025-06-27T09:19:00.922Z"}
[32minfo[39m: Swagger docs available at http://localhost:3000/api-docs {"timestamp":"2025-06-27T09:19:00.922Z"}
[32minfo[39m: Database connection established successfully {"timestamp":"2025-06-27T09:43:06.512Z"}
[32minfo[39m: Database synchronized successfully {"timestamp":"2025-06-27T09:43:06.988Z"}
[32minfo[39m: Server running on port 3000 {"timestamp":"2025-06-27T09:43:06.989Z"}
[32minfo[39m: Swagger docs available at http://localhost:3000/api-docs {"timestamp":"2025-06-27T09:43:06.989Z"}
[31merror[39m: Unable to connect to database: connect ECONNREFUSED 127.0.0.1:5432 {"name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/src/errors/connection/connection-refused-error.ts:8:5)\n    at Client.eval [as _connectionCallback] (/home/project/node_modules/sequelize/src/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:30:11034)\n    at Connection.emit (node:domain:29:5199)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:11034)","timestamp":"2025-06-27T17:19:38.298Z"}
[31merror[39m: Unable to connect to database: connect ECONNREFUSED 127.0.0.1:5432 {"name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/src/errors/connection/connection-refused-error.ts:8:5)\n    at Client.eval [as _connectionCallback] (/home/project/node_modules/sequelize/src/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:30:11034)\n    at Connection.emit (node:domain:29:5199)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:11034)","timestamp":"2025-06-27T17:58:18.554Z"}
[31merror[39m: Unable to connect to database: connect ECONNREFUSED 127.0.0.1:5432 {"name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/src/errors/connection/connection-refused-error.ts:8:5)\n    at Client.eval [as _connectionCallback] (/home/project/node_modules/sequelize/src/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:30:11034)\n    at Connection.emit (node:domain:29:5199)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:11034)","timestamp":"2025-06-27T17:59:27.234Z"}
